### ISSUE TITLE
it work, but has some problems

### ISSUE THREAD

**Issue by 274153705** [nondanee/puppeteer-electron#1]
[#L15](https://github.com/nondanee/puppeteer-electron/blob/master/index.js#L15)

`spawn` The "file" argument must be of type string. Received type object

You use `electron` object , change `electron.app.getPath("exe")` it can work .
Does that be affected?

**Comment by nondanee** [comment]
Only in electron wrapped process without `ELECTRON_RUN_AS_NODE` flag (run `electron script.js` instead of `node script.js`), the `require('electron')` returns an object

Otherwise, it returns a string with the path of electron binary executable file
(This API seems undocumented in electron docs)

Related issues:
https://github.com/electron/electron/issues/8200
https://github.com/electron/electron/issues/4017

**Comment by 274153705** [comment]
Ok , I got it ! Thanks

**Comment by francis-joseph** [comment]
Same issue

**Comment by nondanee** [comment]
Add `typeof` check now, please try the new version.
https://github.com/nondanee/puppeteer-electron/blob/14c84dc4714e8ac6e435f2b9ed341364d11ab07f/index.js#L9
